describe('Login and logout', () => {
  it('Login and logout', () => {
    cy.visit('localhost:4200/')
    cy.get("button").first().click()
    cy.wait(200)
    cy.get("input").first().type('testEmail')
    cy.get("input[type=password]").first().type('testPassword')
    cy.get("button").first().click()
    localStorage.setItem("token","token")
    cy.wait(1000)
    cy.get("button").first().click()
  })
})
describe('Register then login with those credentials', () => {
  it('Register then login with those credentials', () => {
    cy.visit('localhost:4200/')
    cy.get("button").first().click()

    cy.get("a").first().click()

    cy.get("input").first().type('test')
    cy.get("input[type=password]").first().type('test')
    cy.get("input[id=Name]").type("test")
    cy.get("input[id=Surname]").type("test")
    cy.get("button").first().click()
    cy.wait(200)
    cy.get("button").first().click()

    cy.get("input").first().type('test')
    cy.get("input[type=password]").first().type('test')
    cy.get("button").first().click()
    localStorage.setItem("token","token")
  })
})
describe('Login addList and check if list with that name exists', () => {
  it('Login addList and check if list with that name exists', () => {
    cy.visit('localhost:4200/')
    cy.get("button").first().click()
    cy.wait(200)
    cy.get("input").first().type('testEmail')
    cy.get("input[type=password]").first().type('testPassword')
    cy.get("button").first().click()
    localStorage.setItem("token","token")
    cy.wait(1000)
    cy.get("button[id=buttonAddProductList]").first().click()
    cy.wait(1000)
    cy.get("input").first().type("testttt")
    cy.get("input[id=Description]").type("testtt")
    cy.get("button").first().click()
    cy.contains("testttt").should('exist')
  })
})
describe('Login deleteList and check if list not exists', () => {
  it('Login deleteList and check if list not exists', () => {
    cy.visit('localhost:4200/')
    cy.get("button").first().click()
    cy.wait(200)
    cy.get("input").first().type('testEmail')
    cy.get("input[type=password]").first().type('testPassword')
    cy.get("button").first().click()
    localStorage.setItem("token","token")
    cy.wait(1000)
    cy.get("button[id=buttonDeleteProductList]").eq(2).click()
    cy.contains("testttt").should('not.exist')
  })
})
